---
title: "Topics"
output:
  html_document:
    toc: true
    toc_float: true
    collapsed: false
    number_sections: false
    toc_depth: 1
    #code_folding: hide
---


# Graduação Estatística

 - Universidade Federal do Paraná
 
Fevereiro/14 - Dezembro/21

## 1º Ano

- Fundamentos Básicos para Estatística
- Estatística Descritiva e Inferencial Básica
- Cálculo I
- Geometria Analítica
- Seminários
- Estatística Computacional I
- Fundamentos da Programação



## 2º Ano

- Cálculo II
- Álgebra Linear
- Probabilidades A
- Métodos Numéricos
- Estatística Inferencial
- Métodos de Amostragem
- Probabilidades B
- Pesquisa Operacional I

## 3º Ano

- Análise de Regressão Linear
- Planejamentos de Experimentos I
- Controle Estatístico de Qualidade
- Processos Estocásticos Aplicados
- Estatística Não Paramétrica 
- Análise de Dados Categóricos 
- Controle de Processos Industriais 
- Estatística Computacional II
- Modelos Lineares Generalizados 


## 4º Ano

- Teoria do Risco
- Análise de Sobrevivência 
- Modelos Estatísticos Multivariados 
- Métodos de Pesquisa
- Análise de Dados Longitudinais 
- Análise de Séries Temporais
- Extensão de Modelos de Regressão
- Laboratório A (Análise de Componentes Principais e Dados Categóricos)

## 5º Ano

- Laboratório B (Análise de Componentes Principais e Dados Categóricos)

# Curso Data Science 

 - Harve Escola de Inovação

Outubro/20 - Março/21

- Fundamento de dados
- KPIs e Business Questions
- Testes de Hipóteses e Testes AB
- Introdução ao Python
- Python para Ciência de Dados
- SQL
- ETL e Tratamento de Dados
- Orientação a objetos em Python
- Análise de Regressão
- R
- Visualização de Dados 
- Big Data
- IA e Machine Learning

# MBA Data Science and Analytics

 - USP/Esalq

Maio/22 - Janeiro/24

## MÓDULO - DATA SCIENCE E BIG DATA NO AMBIENTE DE NEGÓCIOS

- Big Data e Data Mining
- Metodologias Ágeis
- Tecnologia da Informação (TI) e Inovação Tecnológica
- Introdução ao Java Script
- Engenharia de Dados
- Business Intelligence e Data Visualization
- Análise da Conjuntura Econômica em Cenários de Tecnologias Disruptivas
- Analytics e Gestão de Riscos
- Cloud Computing
- Legislação no Ambiente Digital
- Tópicos Especiais em Tecnologia de Negócios


## MÓDULO - EXPLORATORY ANALYTICS, PREDICTIVE ANALYTICS & MACHINE LEARNING
- Estruturas de Bancos de Dados, Tipos de Variáveis e Escalas de Mensuração
- Introdução ao Machine Learning
- Unsupervised Machine Learning - Clustering
- Unsupervised Machine Learning - Análise Fatorial e PCA
- Unsupervised Machine Learning - Análise de Correspondência Simples e Múltipla
- Supervised Machine Learning - Análise de Regressão Simples e Múltipla
- Supervised Machine Learning - Modelos Logísticos Binários e Multinomiais
- Supervised Machine Learning - Modelos para Dados de Contagem
- Supervised Machine Learning - Modelagem Multinível
- Séries Temporais
 

## MÓDULO - TENDÊNCIAS EM DATA SCIENCE E ANALYTICS
- Data Wrangling
- Análise Espacial
- Outros Modelos de Machine Learning
- Conceitos básicos para Introdução ao Deep Learning
- Deep Learning
- Coleta de Dados: Crawlers e Web Scraping
- Text Mining e Sentiment Analysis
- Pesquisa Operacional e Modelos de Otimização e Simulação
- Gestão da Mudança na Era Digital (Change Management)
